apiVersion: v1
kind: Secret
metadata:
  name: cm-mediator-db-secret
type: Opaque
data:
  {{ $dbConfig := index .Values "eric-data-document-database-pg" }}
  username: {{ default (randAlphaNum 10) $dbConfig.postgresUser | b64enc | quote }}
  password: {{ default (randAlphaNum 10) $dbConfig.postgresPassword | b64enc | quote }}
  super-pwd: {{ default (randAlphaNum 10) $dbConfig.postgresSuperPassword | b64enc | quote }}
  metrics-user: {{ default "exporter"  $dbConfig.metricsUser | b64enc | quote }}
  metrics-pwd: {{ default (randAlphaNum 10) $dbConfig.metricsPwd | b64enc | quote }}
  replica-user: {{ default "replica" $dbConfig.replicaUser | b64enc | quote }}
  replica-pwd: {{ default (randAlphaNum 10) $dbConfig.replicaPwd | b64enc | quote }}
