#
# COPYRIGHT Ericsson 2021 - 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

# Default values for eric-oss-5gpmevent-filetrans-proc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# As default registry path, the global registry path will be used.
global:
  timezone: UTC
  registry:
    url: armdocker.rnd.ericsson.se
    # Secret must be manually created in the namespace, no default value
  pullSecret:
  security:
    tls:
      enabled: false
#    policyBinding:
#      create: true
#    policyReferenceMap:
#      default-restricted-security-policy: "<restricted security policy at customer deployment>"
#  fsGroup:
#    manual: 10000
#    namespace: true
#  # The IP family the service belongs to when service.type is set to ClusterIP.
#  # Options are: IPv4, IPv6
#  internalIPFamily:

#TODO: Enable the tls security when solution is implemented
security:
  tls:
    enabled: false

replicaCount: 1

podDisruptionBudget:
  # Minimum number/percentage of Pods that must remain available during the planned disruption.
  # Value can be expressed as an integer or as a percentage. When specified as a percentage of the Pods,
  # if it does not map to an exact number, Kubernetes rounds up to the nearest integer.
  # minAvailable: 2 # example value for 2 pods defined as integer
  minAvailable: "40%"

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

#Empty labels list for application deployment engineer to add more labels (In Compliance with DR-D1121-068).
labels: {}

images:
  eric-oss-5gpmevent-filetrans-proc:
    name: NAME
    tag: VERSION

imageCredentials:
  eric-oss-5gpmevent-filetrans-proc:
    pullPolicy: IfNotPresent
    repoPath: REPO_PATH
    registry:
    # overrides global registry url
      url: armdocker.rnd.ericsson.se
    #- Secret must be manually created in the namespace, no default value
    pullSecret:
  eric-oss-5gpmevent-filetrans-procTest:
    repoPath: REPO_PATH
    name: NAME
    tag: VERSION

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

annotations: {}

service:
  type: ClusterIP
  port: 8080    # Changed from 80 to 8080 and spring application is hosted on 8080
  endpoints:
    chassisapi:
      tls:
        enforced: required
        verifyClientCertificate: required

ingress:
  enabled: false
  ingressClass: OAM-IngressClass
  hosts:
  - host: chart-example.local
    paths: [/]

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

prometheus:
  path: /actuator/prometheus
  scrape: true

terminationGracePeriodSeconds: 30

resources:
  eric-oss-5gpmevent-filetrans-proc:
    requests:
      memory: 2G
      cpu: "2"
      ephemeral-storage: 3G
    limits:
      memory: 4Gi
      cpu: "3"
      ephemeral-storage: 6G
  eric-oss-5gpmevent-filetrans-procTest:
    requests:
      memory: 128Mi
      cpu: 50m
      ephemeral-storage: ""
    limits:
      memory: 1Gi
      cpu: 256m
      ephemeral-storage: ""
  eric-data-message-bus-kf:
    requests:
      cpu: "200m"
      memory: "128Mi"
      maxCpu: "200m"
      maxMemory: "1024Mi"
  eric-data-document-database-pg:
    requests:
      cpu: "200m"
      memory: "128Mi"
      maxCpu: "200m"
      maxMemory: "1024Mi"
  eric-data-processor-s:
    requests:
      cpu: "200m"
      memory: "128Mi"
      maxCpu: "200m"
      maxMemory: "1024Mi"

autoScaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

topologySpreadConstraints:
  deployment: []
  test: []

tolerations: []

affinity:
  podAntiAffinity: "soft"

connected:
  systems:
    url: "http://eric-eo-subsystem-management/subsystem-manager/v1/subsystems/"

dmm:
  dataCatalog:
    baseUrl: "http://eric-oss-data-catalog:"
    basePort: "9590"
    notificationTopicUri: "/catalog/v1/notification-topic/"
    fileFormatUri: "/catalog/v1/file-format/"
    dataProviderType: "5G"
    dataSpace: "enm"
    dataCategory: "PM_CELLTRACE"

configMap:
  spring:
    kafka:
      topics:
        input:
          partitionAssignmentStrategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
          sessionTimeoutMs: 30000
          replicas: 3
        output:
          acks: all
          compressionType: "lz4"
          partitions: 3
          replicas: 3
          batchSize: "1000000" #1MB
          bufferMemory: "1000000" #1MB
          maxRequestSize: "50000000" #50MB
          linger: 15 #15ms

probes:
  eric-oss-5gpmevent-filetrans-proc:
    livenessProbe:
      failureThreshold: 30
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 10
    readinessProbe:
      failureThreshold: 30
      initialDelaySeconds: 60
      periodSeconds: 10
      timeoutSeconds: 10

eric-data-coordinator-zk:
  enabled: true
  persistentVolumeClaim:
    storageClassName: ""
  global:
    security:
      tls:
        enabled: false
  security:
    tls:
      brAgent:
        enabled: false
  replicas: 1
  persistence:
    persistentVolumeClaim:
      storageClassName: ""
      size: 1Gi
  resources:
    datacoordinatorzk:
      requests:
        cpu: 15m

eric-data-message-bus-kf:
  enabled: true
  persistentVolumeClaim:
    storageClassName: "default"
  jmx:
    enabled: false
  configurationOverrides:
    "log.retention.minutes": 30
  persistence:
    persistentVolumeClaim:
      enabled: false
  nameOverride: eric-pm-events-message-bus-kf
  fullnameOverride: eric-pm-events-message-bus-kf

eric-data-document-database-pg:
  enabled: true
  postgresDatabase: lookup
  postgresPassword: cmpw
  postgresUser: cm
  global:
    security:
      tls:
        enabled: false
  security:
    tls:
      brAgent:
        enabled: false
  credentials:
    kubernetesSecretName: cm-mediator-db-secret
    keyForUserId: username
    keyForUserPw: password
  replicas: 1

eric-data-processor-s:
  volumes: |
    - name: eric-data-engine-sk-checkpoint
      nfs:
        path: "/exports"
        server: 10.150.66.239
  volumeMounts: |
    - name: eric-data-engine-sk-checkpoint
      mountPath: "/checkpoints"
      subPath: ci
      readOnly: false

eric-event-data-collector:
  enabled: true
  ctrParser:
    schemaRegistry:
      serviceName: eric-oss-schema-registry-sr
      port: "8081"
  volumes: |
    - name: eric-event-data-collector-pmdata
      nfs:
        server: 10.150.66.239
        path: "/exports"
  volumeMounts: |
    - name: eric-event-data-collector-pmdata
      mountPath: "/ctr_data"
      subPath: 15k1rop
      readOnly: true

schema-importer:
  schemaregistry:
    clientServiceName: "eric-oss-schema-registry-sr"
  schemaImporterDir: /exports/avro_schemas
  dataDirectory: /exports
  dataMountServer: 10.150.66.239

eric-pm-server:
  enabled: true
  rbac:
    appMonitoring:
      enabled: true
  server:
    service:
      type: NodePort
    serviceAccountName: default
    ingress:
      enabled: true
      hosts:
        - pm.server.ieatenmpcbfl-219.athtem.eei.ericsson.se
  clusterRoleName: aia-eson-pm-server

eric-cm-mediator:
  enabled: true
  backend:
    hostname: eric-data-document-database-pg
    dbname: lookup
  kafka:
    hostname: eric-pm-events-message-bus-kf
  service:
    type: NodePort
  credentials:
    kubernetesSecretName: cm-mediator-db-secret
    keyForUserId: username
    keyForUserPw: password
  global:
    security:
      tls:
        enabled: false

eric-data-search-engine:
  client:
    jvmHeap: 128Mi
    replicas: 2
    resources:
      limits:
        memory: 512Mi
  data:
    jvmHeap: 128Mi
    accessMode: ReadWriteOnce
    storageAllocation: 2Gi
    replicas: 2
    resources:
      limits:
        memory: 512Mi
  master:
    jvmHeap: 128Mi
    resources:
      limits:
        memory: 512Mi

eric-data-visualizer-kb:
  service:
    type: NodePort
    externalPort: 31000
  ingress:
    enabled: true
    hosts:
      - kb.server.ibd1.ericsson.se
  logtransformer:
    host: eric-log-transformer

eric-log-shipper:
  useFullCfg: true
  additionalVolumeMounts: |
    - name: dockerlog
      mountPath: /var/lib/docker/
  additionalVolumes: |
    - name: dockerlog
      hostPath:
        path: /var/lib/docker/
  logshipper:
    serviceAccountName: monitoring
    cfgData: |
      filebeat.prospectors:
      - input_type: log
        paths:
          - /var/lib/docker/overlay2/*/diff/opt/spark-*/work-dir/*/std*
          - /var/lib/docker/overlay2/*/diff/opt/spark-*/work-dir/*/*/std*
          - /var/lib/docker/containers/*/*.log
        fields:
          logplane: kubelog
        fields_under_root: true
        tail_files: true
        processors:
          - add_kubernetes_metadata:
              in_cluster: true
      output.logstash:
        hosts: '${LOGSTASH_HOSTS}'

eric-log-transformer:
  jvmHeap: 1G
  replicaCount: 2
  resources:
    limits:
      cpu: 200m
      memory: 512Mi

celltrace:
  persistentVolumeClaim:
    enabled: false
    claimName: ""
    mountPath: "/stubbed-enm/fls/files"

eric-oss-schema-registry-sr:
  enabled: true
  service:
    port: "8081"
  messagebuskf:
    clientServiceName: eric-pm-events-message-bus-kf