#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
data:
  connected_systems_url: {{ .Values.connected.systems.url | quote }}
  spring_kafka_topics_output_partitions: {{ .Values.configMap.spring.kafka.topics.output.partitions | quote }}
  spring_kafka_topics_output_acks: {{ .Values.configMap.spring.kafka.topics.output.acks | quote }}
  spring_kafka_topics_output_replicas: {{ .Values.configMap.spring.kafka.topics.output.replicas | quote }}
  spring_kafka_topics_output_compression_type: {{ .Values.configMap.spring.kafka.topics.output.compressionType | quote }}
  spring_kafka_topics_output_batch_size: {{ .Values.configMap.spring.kafka.topics.output.batchSize | quote }}
  spring_kafka_topics_output_buffer_memory: {{ .Values.configMap.spring.kafka.topics.output.bufferMemory | quote }}
  spring_kafka_topics_output_max_request_size: {{ .Values.configMap.spring.kafka.topics.output.maxRequestSize | quote }}
  spring_kafka_topics_output_linger: {{ .Values.configMap.spring.kafka.topics.output.linger | quote }}
  spring_kafka_topics_input_session_timeout_ms: {{ .Values.configMap.spring.kafka.topics.input.sessionTimeoutMs | quote }}
  spring_kafka_topics_input_partition_assignment_strategy: {{ .Values.configMap.spring.kafka.topics.input.partitionAssignmentStrategy | quote }}
  dmm_data_catalog_base_url: {{ .Values.dmm.dataCatalog.baseUrl | quote }}
  dmm_data_catalog_base_port: {{ .Values.dmm.dataCatalog.basePort | quote }}
  dmm_data_catalog_notification_topic_uri: {{ .Values.dmm.dataCatalog.notificationTopicUri | quote }}
  dmm_data_catalog_file_format_uri: {{ .Values.dmm.dataCatalog.fileFormatUri | quote }}
  dmm_data_catalog_data_provider_type: {{ .Values.dmm.dataCatalog.dataProviderType | quote }}
  dmm_data_catalog_data_space: {{ .Values.dmm.dataCatalog.dataSpace | quote }}
  dmm_data_catalog_data_category: {{ .Values.dmm.dataCatalog.dataCategory | quote }}
  application.properties: |
    management.endpoint.metrics.enabled=true
    management.endpoints.web.exposure.include=*
    management.endpoint.prometheus.enabled=true
    management.metrics.export.prometheus.enabled=true
    management.metrics.web.server.auto-time-requests=true
kind: ConfigMap
metadata:
  name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
  labels:
  {{- include "eric-oss-5gpmevent-filetrans-proc.labels" . | indent 4 }}
  {{- if .Values.labels }}
    {{ .Values.labels | toYaml | indent 4 }}
  {{- end }}
  annotations:
{{- include "eric-oss-5gpmevent-filetrans-proc.prometheus" . | nindent 4 }}
{{- include "eric-oss-5gpmevent-filetrans-proc.product-info" . | indent 4 }}
{{- include "eric-oss-5gpmevent-filetrans-proc.config-annotations" . | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eric-oss-5gpmevent-filetrans-proc.fullname" . }}
  labels:
{{- include "eric-oss-5gpmevent-filetrans-proc.labels" . | nindent 4 }}
  annotations:
{{ include "eric-oss-5gpmevent-filetrans-proc.product-info" . | indent 4 }}
{{- include "eric-oss-5gpmevent-filetrans-proc.config-annotations" . | indent 4 }}
spec:
{{- if not .Values.autoScaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: {{ .Values.updateStrategy.type | quote }}
    {{- if and (eq .Values.updateStrategy.type "RollingUpdate") .Values.updateStrategy.rollingUpdate }}
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.updateStrategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ include "eric-oss-5gpmevent-filetrans-proc.version" . }}
      annotations:
{{ include "eric-oss-5gpmevent-filetrans-proc.prometheus" . | nindent 8 }}
{{ include "eric-oss-5gpmevent-filetrans-proc.product-info" . | indent 8 }}
{{- include "eric-oss-5gpmevent-filetrans-proc.config-annotations" . | indent 8 }}
    spec:
      {{- if include "eric-oss-5gpmevent-filetrans-proc.pullSecret" . }}
      imagePullSecrets:
        - name: {{ include "eric-oss-5gpmevent-filetrans-proc.pullSecret" . | quote}}
      {{- end }}
      serviceAccountName: {{ template "eric-oss-5gpmevent-filetrans-proc.fullname" . }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds:
        {{- include "eric-oss-5gpmevent-filetrans-proc.terminationGracePeriodSeconds" . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: {{ include "eric-oss-5gpmevent-filetrans-proc.fsGroup.coordinated" . }}
      volumes:
{{ include "eric-event-data-collector.volumes" . | indent 8 -}}
        - name: tmp-volume
          emptyDir: { }
        - name: config-volume
          configMap:
            name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
        {{- if  .Values.celltrace.persistentVolumeClaim.enabled }}
        - name: celltrace-data
          persistentVolumeClaim:
            claimName: {{ .Values.celltrace.persistentVolumeClaim.claimName }}
        {{- end }}
      containers:
        - name: eric-oss-5gpmevent-filetrans-proc
          image: {{ template "eric-oss-5gpmevent-filetrans-proc.registryUrl" . }}/{{ index .Values "imageCredentials" "eric-oss-5gpmevent-filetrans-proc" "repoPath" }}/{{ index .Values "images" "eric-oss-5gpmevent-filetrans-proc" "name" }}:{{ index .Values "images" "eric-oss-5gpmevent-filetrans-proc" "tag" }}
          imagePullPolicy: {{ index .Values "imageCredentials" "eric-oss-5gpmevent-filetrans-proc" "pullPolicy" | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - all
          volumeMounts:
{{ include "eric-event-data-collector.volumeMounts" . | indent 12 -}}
            - name: tmp-volume
              mountPath: /tmp
            - name: config-volume
              mountPath: /config
            {{- if  .Values.celltrace.persistentVolumeClaim.enabled }}
            - name: celltrace-data
              mountPath: {{ .Values.celltrace.persistentVolumeClaim.mountPath }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- if (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "livenessProbe" "initialDelaySeconds") }}
            {{ print "initialDelaySeconds: " (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "livenessProbe" "initialDelaySeconds") }}
            {{- end }}
            {{- if (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "livenessProbe" "failureThreshold") }}
            {{ print "failureThreshold: " (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "livenessProbe" "failureThreshold") }}
            {{- end }}
            {{- if (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "livenessProbe" "periodSeconds") }}
            {{ print "periodSeconds: " (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "livenessProbe" "periodSeconds") }}
            {{- end }}
            {{- if (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "livenessProbe" "timeoutSeconds") }}
            {{ print "timeoutSeconds: " (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "livenessProbe" "timeoutSeconds") }}
            {{- end }}
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            {{- if (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "readinessProbe" "initialDelaySeconds") }}
            {{ print "initialDelaySeconds: " (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "readinessProbe" "initialDelaySeconds") }}
            {{- end }}
            {{- if (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "readinessProbe" "failureThreshold") }}
            {{ print "failureThreshold: " (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "readinessProbe" "failureThreshold") }}
            {{- end }}
            {{- if (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "readinessProbe" "periodSeconds") }}
            {{ print "periodSeconds: " (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "readinessProbe" "periodSeconds") }}
            {{- end }}
            {{- if (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "readinessProbe" "timeoutSeconds") }}
            {{ print "timeoutSeconds: " (index .Values "probes" "eric-oss-5gpmevent-filetrans-proc" "readinessProbe" "timeoutSeconds") }}
            {{- end }}
            httpGet:
              path: /actuator/health
              port: http
          env:
          - name: CONNECTED_SYSTEMS_URL
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: connected_systems_url
          - name: SPRING_KAFKA_TOPICS_OUTPUT_PARTITIONS
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: spring_kafka_topics_output_partitions
          - name: SPRING_KAFKA_TOPICS_OUTPUT_ACKS
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: spring_kafka_topics_output_acks
          - name: SPRING_KAFKA_TOPICS_OUTPUT_REPLICAS
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: spring_kafka_topics_output_replicas
          - name: SPRING_KAFKA_TOPICS_OUTPUT_COMPRESSION_TYPE
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: spring_kafka_topics_output_compression_type
          - name: SPRING_KAFKA_TOPICS_OUTPUT_BATCH_SIZE
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: spring_kafka_topics_output_batch_size
          - name: SPRING_KAFKA_TOPICS_OUTPUT_BUFFER_MEMORY
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: spring_kafka_topics_output_buffer_memory
          - name: SPRING_KAFKA_TOPICS_OUTPUT_MAX_REQUEST_SIZE
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: spring_kafka_topics_output_max_request_size
          - name: SPRING_KAFKA_TOPICS_OUTPUT_LINGER
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: spring_kafka_topics_output_linger
          - name: SPRING_KAFKA_TOPICS_INPUT_SESSION_TIMEOUT_MS
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: spring_kafka_topics_input_session_timeout_ms
          - name: SPRING_KAFKA_TOPICS_INPUT_PARTITION_ASSIGNMENT_STRATEGY
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: spring_kafka_topics_input_partition_assignment_strategy
          - name: DMM_DATA_CATALOG_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: dmm_data_catalog_base_url
          - name: DMM_DATA_CATALOG_BASE_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: dmm_data_catalog_base_port
          - name: DMM_DATA_CATALOG_NOTIFICATION_TOPIC_URI
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: dmm_data_catalog_notification_topic_uri
          - name: DMM_DATA_CATALOG_FILE_FORMAT_URI
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: dmm_data_catalog_file_format_uri
          - name: DMM_DATA_CATALOG_DATA_PROVIDER_TYPE
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: dmm_data_catalog_data_provider_type
          - name: DMM_DATA_CATALOG_DATA_SPACE
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: dmm_data_catalog_data_space
          - name: DMM_DATA_CATALOG_DATA_CATEGORY
            valueFrom:
              configMapKeyRef:
                name: {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}-configmap
                key: dmm_data_catalog_data_category
          - name: TZ
            value: {{ template "eric-oss-5gpmevent-filetrans-proc.timezone" . }}
      {{- if .Values.global }}
        {{- if .Values.global.security }}
          {{- if .Values.global.security.tls }}
            {{- if .Values.global.security.tls.enabled }}
          - name: CONNECT_MODE
            value: "tls"
            {{- if (eq .Values.service.endpoints.chassisapi.tls.enforced "required") }}
          - name: TLS_MODE
            value: "only_tls"
            {{- if (eq .Values.service.endpoints.chassisapi.tls.verifyClientCertificate "required") }}
          - name: TLS_CA
            value: "ca_path"
            {{- end }}
            {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
          resources:
            requests:
            {{- if (index .Values "resources" "eric-oss-5gpmevent-filetrans-proc" "requests" "cpu") }}
              cpu: {{ (index .Values "resources" "eric-oss-5gpmevent-filetrans-proc" "requests" "cpu" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-5gpmevent-filetrans-proc" "requests" "memory") }}
              memory: {{ (index .Values "resources" "eric-oss-5gpmevent-filetrans-proc" "requests" "memory" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-5gpmevent-filetrans-proc" "requests" "ephemeral-storage") }}
            {{ println "  ephemeral-storage:" (index .Values "resources" "eric-oss-5gpmevent-filetrans-proc" "requests" "ephemeral-storage" | quote) }}
            {{- end }}
            limits:
            {{- if (index .Values "resources" "eric-oss-5gpmevent-filetrans-proc" "limits" "cpu") }}
              cpu: {{ (index .Values "resources" "eric-oss-5gpmevent-filetrans-proc" "limits" "cpu" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-5gpmevent-filetrans-proc" "limits" "memory") }}
              memory: {{ (index .Values "resources" "eric-oss-5gpmevent-filetrans-proc" "limits" "memory" | quote) }}
            {{- end }}
            {{- if (index .Values "resources" "eric-oss-5gpmevent-filetrans-proc" "limits" "ephemeral-storage") }}
            {{ println "  ephemeral-storage:" (index .Values "resources" "eric-oss-5gpmevent-filetrans-proc" "limits" "ephemeral-storage" | quote) }}
            {{- end }}
      nodeSelector: {{ include "eric-oss-5gpmevent-filetrans-proc.nodeSelector" . | nindent 6 -}}
      {{- if .Values.tolerations }}
      tolerations:
        {{- include "eric-oss-5gpmevent-filetrans-proc.tolerations" . | nindent 8 }}
      {{- end }}

      {{- with .Values.topologySpreadConstraints.deployment }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 6 }}
      {{- end }}

      {{- if eq .Values.affinity.podAntiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}
            topologyKey: "kubernetes.io/hostname"
      {{- else if eq .Values.affinity.podAntiAffinity  "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ include "eric-oss-5gpmevent-filetrans-proc.name" . }}
              topologyKey: "kubernetes.io/hostname"
      {{- end }}


