apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "eric-oss-5gpmevent-filetrans-proc.fullname" . }}-pv
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  storageClassName: eric-nfs
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"