apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: testpvvolumeclass
  annotations:
    "helm.sh/hook": pre-install,post-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate