{
 "title": "eric-oss-5gpmevent-filetrans-proc Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU: POC pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\".*5gpmevent.*\", namespace=\"$Namespace\", container!=\"\"}[180s])",
     "legendFormat": "CUR: {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{pod=~\".*poc.*\", container!=\"\", resource=\"cpu\" , namespace=\"$Namespace\"})",
     "legendFormat": "LIM: {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{pod=~\".*poc.*\", container!=\"\", resource=\"cpu\" , namespace=\"$Namespace\"})",
     "legendFormat": "REQ: {{pod}}"
    }
   ]
  },
  {
   "title": "Memory: POC pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\".*5gpmevent.*\", image!=\"\", container!=\"\", container_name!=\"POD\", namespace=\"$Namespace\"}",
     "legendFormat": "CUR: {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{pod=~\".*5gpmevent.*\", container!=\"\", resource=\"memory\" , namespace=\"$Namespace\"})",
     "legendFormat": "LIM: {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{pod=~\".*5gpmevent.*\",  container!=\"\", resource=\"memory\", namespace=\"$Namespace\"})",
     "legendFormat": "REQ: {{pod}}"
    }
   ]
  },
  {
   "title": "Heap Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{kubernetes_pod_name=~\".*5gpmevent.*\", kubernetes_namespace=\"$Namespace\"}",
     "legendFormat": " {{kubernetes_pod_name}}: {{id}}"
    }
   ]
  },
  {
   "title": "GC Pause Seconds Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "increase(jvm_gc_pause_seconds_max{kubernetes_namespace=\"$Namespace\", kubernetes_pod_name=~\".*5gpmevent.*\"}[2m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Daemon Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{kubernetes_namespace=\"$Namespace\", kubernetes_pod_name=~\".*5gpmevent.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{kubernetes_namespace=\"$Namespace\", kubernetes_pod_name=~\".*5gpmevent.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{kubernetes_namespace=\"$Namespace\", kubernetes_pod_name=~\".*5gpmevent.*\"}",
     "legendFormat": "{{kubernetes_pod_name}} {{state}}"
    }
   ]
  },
  {
   "title": "Peak Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "jvm_threads_peak_threads{kubernetes_namespace=\"$Namespace\", kubernetes_pod_name=~\".*5gpmevent.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Data Volume of Processed 5G Event Files (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "eric_oss_5gpmevent_filetrans_proc:processed_file_data_volumue{kubernetes_namespace=\"$Namespace\", kubernetes_pod_name=~\".*5gpmevent.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of Processed 5G Event Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "eric_oss_5gpmevent_filetrans_proc:event_files_processed_total{kubernetes_namespace=\"$Namespace\", kubernetes_pod_name=~\".*5gpmevent.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}