apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-event-data-collector.name" . }}-flow-config
  labels:
    app.kubernetes.io/name: {{ include "eric-event-data-collector.name" . }}
    app.kubernetes.io/version: {{ include "eric-event-data-collector.version" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app: {{  template "eric-event-data-collector.name" . }}
    {{- include "eric-event-data-collector.user-labels" . | indent 4 }}
  annotations:
    {{- include "eric-event-data-collector.product-info" . | indent 4 }}
data:
  flow.xml: {{ quote (index .Values.ctrParser.flow .Values.ctrParser.flow.flowFile) }}
  logback.xml: {{ quote (index .Values.ctrParser.logging .Values.ctrParser.logging.logbackFile) }}
  PUBLISHER_INTEGRATION_POINT.json: {{ quote (index .Values.ctrParser.ipl.publisher.publisherFileContent) }}
  SUBSCRIBER_INTEGRATION_POINT.json: {{ quote (index .Values.ctrParser.ipl.subscriber.subscriberFileContent) }}
  CMMEDIATOR_SUBSCRIBER_INTEGRATION_POINT.json: {{ quote (index .Values.ctrParser.ipl.subscriber.cmMediator_SubscriberFileContent) }}
  eventListFilter.json: {{ quote (index .Values.ctrParser.ipl.eventFilterFileContent) }}
