apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "eric-event-data-collector.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "eric-event-data-collector.name" . }}
    app.kubernetes.io/version: {{ include "eric-event-data-collector.version" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "eric-event-data-collector.chart" . }}
    {{- include "eric-event-data-collector.user-labels" . | indent 4 }}
  annotations:
    {{- include "eric-event-data-collector.product-info" . | indent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eric-event-data-collector.name" . | quote }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}