apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-event-data-collector.name" . }}-sa
  labels:
    app.kubernetes.io/name: {{ include "eric-event-data-collector.name" . }}
    app.kubernetes.io/version: {{ include "eric-event-data-collector.version" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "eric-event-data-collector.chart" . }}
  annotations:
  {{- include "eric-event-data-collector.product-info" . | indent 4 }}
automountServiceAccountToken: false